const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Flash,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Rotate,
		C3.Plugins.Spritefont2,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet
	];
};
self.C3_JsPropNameTable = [
	{Tilemap: 0},
	{Janela: 0},
	{Solid: 0},
	{Suporte: 0},
	{Flash: 0},
	{Bau: 0},
	{Platform: 0},
	{Caixa: 0},
	{Porta: 0},
	{Chave: 0},
	{Bomba: 0},
	{ScrollTo: 0},
	{Jogador: 0},
	{Sensor_Solido: 0},
	{Keyboard: 0},
	{Direcao: 0},
	{Patrulheiro: 0},
	{Sensor_Patrulheiro_Direita: 0},
	{Sensor_Patrulheiro_Esquerda: 0},
	{Canhao: 0},
	{Canhao_: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{Rotate: 0},
	{Bala: 0},
	{Sensor_Canhao: 0},
	{Vida_HUD: 0},
	{Itens_HUD: 0},
	{Black_Blackground: 0},
	{Jogador_Dialogo: 0},
	{SpriteFont: 0},
	{chave: 0},
	{Chefao: 0},
	{Audio: 0},
	{Vidas: 0}
];

self.InstanceType = {
	Tilemap: class extends self.ITilemapInstance {},
	Janela: class extends self.ISpriteInstance {},
	Suporte: class extends self.ISpriteInstance {},
	Bau: class extends self.ISpriteInstance {},
	Caixa: class extends self.ISpriteInstance {},
	Porta: class extends self.ISpriteInstance {},
	Jogador: class extends self.ISpriteInstance {},
	Sensor_Solido: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Patrulheiro: class extends self.ISpriteInstance {},
	Sensor_Patrulheiro_Direita: class extends self.ISpriteInstance {},
	Sensor_Patrulheiro_Esquerda: class extends self.ISpriteInstance {},
	Canhao: class extends self.ISpriteInstance {},
	Canhao_: class extends self.ISpriteInstance {},
	Bala: class extends self.ISpriteInstance {},
	Sensor_Canhao: class extends self.ISpriteInstance {},
	Vida_HUD: class extends self.ISpriteInstance {},
	Itens_HUD: class extends self.ISpriteInstance {},
	Black_Blackground: class extends self.ISpriteInstance {},
	Jogador_Dialogo: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	chave: class extends self.ISpriteInstance {},
	Bomba: class extends self.ISpriteInstance {},
	Chefao: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {}
}